# Generated by Django 4.2.7 on 2025-11-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoAccademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(help_text='Formato: YYYY-YYYY (es: 2023-2024)', max_length=9, unique=True, verbose_name='Anno Accademico')),
                ('data_inizio', models.DateField(verbose_name='Data Inizio')),
                ('data_fine', models.DateField(verbose_name='Data Fine')),
                ('attivo', models.BooleanField(default=False, verbose_name='Anno Corrente')),
            ],
            options={
                'verbose_name': 'Anno Accademico',
                'verbose_name_plural': 'Anni Accademici',
                'ordering': ['-anno'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine Visualizzazione')),
            ],
            options={
                'verbose_name': 'Categoria Corso',
                'verbose_name_plural': 'Categorie Corsi',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Comune')),
                ('provincia', models.CharField(blank=True, max_length=2, verbose_name='Sigla Provincia')),
                ('cap', models.CharField(blank=True, max_length=5, verbose_name='CAP')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField(unique=True, verbose_name='Codice Corso')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Corso')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione Dettagliata')),
                ('visibile', models.BooleanField(default=True, verbose_name='Visibile nelle Iscrizioni')),
                ('numero_min_partecipanti', models.IntegerField(blank=True, null=True, verbose_name='N° Minimo Partecipanti')),
                ('numero_max_partecipanti', models.IntegerField(blank=True, null=True, verbose_name='N° Massimo Partecipanti')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriacorso', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
                'ordering': ['codice', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome e Cognome')),
                ('titolo', models.CharField(blank=True, max_length=50, verbose_name='Titolo/Prefisso')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('cellulare', models.CharField(blank=True, max_length=20, verbose_name='Cellulare')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('comune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comune', verbose_name='Comune')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docenti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EdizioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_custom', models.CharField(blank=True, max_length=255, verbose_name='Descrizione Personalizzata')),
                ('giorni_settimana', models.CharField(help_text='Es: Lunedì, Mercoledì', max_length=100, verbose_name='Giorni della Settimana')),
                ('ora_inizio', models.TimeField(verbose_name='Ora Inizio')),
                ('ora_fine', models.TimeField(verbose_name='Ora Fine')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annoaccademico', verbose_name='Anno Accademico')),
            ],
            options={
                'verbose_name': 'Edizione Corso',
                'verbose_name_plural': 'Edizioni Corsi',
                'ordering': ['-anno_accademico', 'quadrimestre', 'corso__nome'],
            },
        ),
        migrations.CreateModel(
            name='GruppoCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Gruppo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Gruppo Corso',
                'verbose_name_plural': 'Gruppi Corsi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lezione', models.DateField(verbose_name='Data Lezione')),
                ('descrizione', models.CharField(blank=True, max_length=255, verbose_name='Argomento/Descrizione')),
                ('ore_lezione', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Ore Lezione')),
                ('numero_presenti', models.IntegerField(default=0, verbose_name='Numero Presenti')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.docente', verbose_name='Docente Effettivo')),
                ('edizione_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lezioni', to='core.edizionecorso', verbose_name='Edizione Corso')),
            ],
            options={
                'verbose_name': 'Lezione',
                'verbose_name_plural': 'Lezioni',
                'ordering': ['-data_lezione', 'edizione_corso'],
                'unique_together': {('edizione_corso', 'data_lezione')},
            },
        ),
        migrations.CreateModel(
            name='ProfessioneAttuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True, verbose_name='Professione')),
            ],
            options={
                'verbose_name': 'Professione Attuale',
                'verbose_name_plural': 'Professioni Attuali',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionePassata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True, verbose_name='Professione')),
            ],
            options={
                'verbose_name': 'Professione Passata',
                'verbose_name_plural': 'Professioni Passate',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Quadrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, '1° Quadrimestre (Ottobre-Gennaio)'), (2, '2° Quadrimestre (Febbraio-Aprile)')], unique=True, verbose_name='Quadrimestre')),
            ],
            options={
                'verbose_name': 'Quadrimestre',
                'verbose_name_plural': 'Quadrimestri',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TitoloStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50, unique=True, verbose_name='Titolo di Studio')),
            ],
            options={
                'verbose_name': 'Titolo di Studio',
                'verbose_name_plural': 'Titoli di Studio',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Iscritto',
            fields=[
                ('matricola', models.AutoField(primary_key=True, serialize=False, verbose_name='Matricola')),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, verbose_name='Sesso')),
                ('titolo', models.CharField(blank=True, max_length=10, verbose_name='Titolo (Sig./Sig.ra)')),
                ('nominativo', models.CharField(max_length=255, verbose_name='Nome e Cognome')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Codice Fiscale')),
                ('luogo_nascita', models.CharField(blank=True, max_length=100, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di Nascita')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('cellulare', models.CharField(blank=True, max_length=20, verbose_name='Cellulare')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ha_whatsapp', models.BooleanField(default=False, verbose_name='Ha WhatsApp')),
                ('situazione', models.CharField(blank=True, choices=[('Celibe/Nubile', 'Celibe/Nubile'), ('Coniugato/a', 'Coniugato/a'), ('Vedovo/a', 'Vedovo/a'), ('Divorziato/a', 'Divorziato/a')], max_length=20, verbose_name='Stato Civile')),
                ('e_pensionato', models.BooleanField(default=False, verbose_name='È Pensionato')),
                ('riceve_posta', models.BooleanField(default=True, verbose_name='Riceve Posta Cartacea')),
                ('e_collaboratore', models.BooleanField(default=False, verbose_name='È Collaboratore')),
                ('e_assistente', models.BooleanField(default=False, verbose_name='Può essere Assistente')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('comune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comune', verbose_name='Comune')),
                ('coniuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.iscritto', verbose_name='Coniuge (se iscritto)')),
                ('professione_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professioneattuale', verbose_name='Professione Attuale')),
                ('professione_passata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professionepassata', verbose_name='Professione Passata')),
                ('titolo_studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.titolostudio', verbose_name='Titolo di Studio')),
            ],
            options={
                'verbose_name': 'Iscritto',
                'verbose_name_plural': 'Iscritti',
                'ordering': ['nominativo'],
            },
        ),
        migrations.AddField(
            model_name='edizionecorso',
            name='assistente',
            field=models.ForeignKey(blank=True, limit_choices_to={'e_assistente': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi_come_assistente', to='core.iscritto', verbose_name='Assistente'),
        ),
        migrations.AddField(
            model_name='edizionecorso',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corso', verbose_name='Corso'),
        ),
        migrations.AddField(
            model_name='edizionecorso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corsi_come_docente', to='core.docente', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='edizionecorso',
            name='quadrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quadrimestre', verbose_name='Quadrimestre'),
        ),
        migrations.AddField(
            model_name='edizionecorso',
            name='vice_assistente',
            field=models.ForeignKey(blank=True, limit_choices_to={'e_assistente': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi_come_vice', to='core.iscritto', verbose_name='Vice Assistente'),
        ),
        migrations.AddField(
            model_name='corso',
            name='gruppo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gruppocorso', verbose_name='Gruppo'),
        ),
        migrations.CreateModel(
            name='Autorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome e Cognome')),
                ('titolo', models.CharField(blank=True, max_length=50, verbose_name='Titolo/Prefisso')),
                ('carica', models.CharField(max_length=100, verbose_name='Carica')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('comune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comune', verbose_name='Comune')),
            ],
            options={
                'verbose_name': 'Autorità',
                'verbose_name_plural': 'Autorità',
                'ordering': ['carica', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PresenzaLezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('iscritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscritto', verbose_name='Iscritto')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='core.lezione', verbose_name='Lezione')),
            ],
            options={
                'verbose_name': 'Presenza Lezione',
                'verbose_name_plural': 'Presenze Lezioni',
                'ordering': ['lezione', 'iscritto__nominativo'],
                'unique_together': {('lezione', 'iscritto')},
            },
        ),
        migrations.CreateModel(
            name='IscrizioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricevuta', models.IntegerField(blank=True, null=True, verbose_name='Numero Ricevuta')),
                ('data_iscrizione', models.DateField(verbose_name='Data Iscrizione')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annoaccademico', verbose_name='Anno Accademico')),
                ('edizione_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='core.edizionecorso', verbose_name='Corso')),
                ('iscritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscritto', verbose_name='Iscritto')),
            ],
            options={
                'verbose_name': 'Iscrizione Corso',
                'verbose_name_plural': 'Iscrizioni Corsi',
                'ordering': ['-anno_accademico', 'edizione_corso', 'iscritto__nominativo'],
                'unique_together': {('anno_accademico', 'edizione_corso', 'iscritto')},
            },
        ),
        migrations.CreateModel(
            name='IscrizioneAnnoAccademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricevuta', models.IntegerField(help_text='Numero progressivo ricevuta', verbose_name='Numero Ricevuta')),
                ('data_iscrizione', models.DateField(verbose_name='Data Iscrizione')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annoaccademico', verbose_name='Anno Accademico')),
                ('iscritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscritto', verbose_name='Iscritto')),
            ],
            options={
                'verbose_name': 'Iscrizione Anno Accademico',
                'verbose_name_plural': 'Iscrizioni Anno Accademico',
                'ordering': ['-anno_accademico', 'data_iscrizione'],
                'unique_together': {('anno_accademico', 'iscritto')},
            },
        ),
        migrations.AddIndex(
            model_name='iscritto',
            index=models.Index(fields=['nominativo'], name='core_iscrit_nominat_3fd02d_idx'),
        ),
        migrations.AddIndex(
            model_name='iscritto',
            index=models.Index(fields=['codice_fiscale'], name='core_iscrit_codice__969514_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edizionecorso',
            unique_together={('anno_accademico', 'corso', 'quadrimestre', 'giorni_settimana', 'ora_inizio')},
        ),
    ]
