# Generated by Django 4.2.7 on 2026-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quadrimestre",
            name="numero",
            field=models.IntegerField(
                choices=[
                    (0, "Non assegnato / Annuale"),
                    (1, "1° Quadrimestre (Ottobre-Gennaio)"),
                    (2, "2° Quadrimestre (Febbraio-Aprile)"),
                    (3, "Entrambi i Quadrimestri"),
                ],
                unique=True,
                verbose_name="Quadrimestre",
            ),
        ),
    ]
