# Generated by Django 4.2.7 on 2026-07-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_quadrimestre_numero"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Autorita",
        ),
    ]
